### ISSUE TITLE
Requesting for code execution guidance. 

### ISSUE THREAD

**Issue by tkamaal** [googlecodelabs/androidthings-googleassistant#5]
Hello,

I have couple of questions regarding running the repo on Raspberry Pi 3. 

**Aim:**
To run androidthings-googleassistant apk on Raspberry Pi 3 by dumping the apk file from Android Studio installed on Windows 7. 

**So far:**
I have installed Android Studio on Windows 7 and cloned the repo. I was following the steps provided in readme to run the app on Raspberry pi.

1. pip install google-auth-oauthlib[tool]
google-oauthlib-tool --client-secrets client_secret_NNNN.json \
                     --credentials app/src/main/res/raw/credentials.json \
                     --scope https://www.googleapis.com/auth/assistant-sdk-prototype \
                     --save
Worked in windows 7 terminal. After running this command, I did check the credentials.json file. All the fields in json file had been updated. After this, I did click on run in Android Studio, I got the following error. 

![error_info](https://user-images.githubusercontent.com/27974027/34500564-2508922e-efc0-11e7-8d8f-6d47ab6b701d.JPG)

2. adb fails in Android studio but works fine in terminal.  I receive the following error in Android Studio. I tried to resolve this error by killing the adb process in task manager and restarting Android studio. Which didn't help my cause. 

![adb_error_info](https://user-images.githubusercontent.com/27974027/34500612-59cb35a2-efc0-11e7-94eb-653ed7f977cb.JPG)

Please, provide some information that would help me to solve this problem. Currently, I'm running this app [sample-button](https://github.com/androidthings/sample-button) on Raspberry Pi 3 without any issues.

**Comment by Fleker** [comment]
I don't know why `adb` would not work within Android Studio.

For your original issue, can you move `app/src/main/res/raw/credentials.json` to `shared/src/main/res/raw/credentials.json` and re-compile?

**Comment by tkamaal** [comment]
Thank you. That got rid of the error but I still can't run the app on Pi. The app keeps restarting. 

Following was the error message on Android Studio. 

Connected to process 1904 on device google-iot_rpi3-10.160.3.131:5555
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/InstantRun: starting instant run server: is main process
I/AssistantActivity: starting assistant demo
D/AssistantActivity: enumerating devices
I/AssistantActivity: initializing DAC trigger
I/AssistantActivity: setting volume to: 15
D/AudioTrack: Client defaulted notificationFrames to 460 for frameCount 1380
E/AudioRecord: AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.androidthings.assistant, PID: 1904
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.androidthings.assistant/com.example.androidthings.assistant.AssistantActivity}: java.lang.UnsupportedOperationException: Cannot create AudioRecord
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                   Caused by: java.lang.UnsupportedOperationException: Cannot create AudioRecord
                      at android.media.AudioRecord$Builder.build(AudioRecord.java:626)
                      at com.example.androidthings.assistant.AssistantActivity.onCreate(AssistantActivity.java:351)
                      at android.app.Activity.performCreate(Activity.java:7000)
                      at android.app.Activity.performCreate(Activity.java:6991)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                      at android.os.Handler.dispatchMessage(Handler.java:106) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6494) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
Application terminated.
 
./gradlew assembleDebug - Ran successfully in Android Studio by modifying it to **gradlew assembleDebug** 

**I believe this error may be cos of not running the following command successfully.
adb install -g app/build/outputs/apk/app-debug.apk** 

Also, I do not see a debug.apk in the following directory app/build/outputs/apk/app-debug.apk. Infact, there is no outputs folder in build directory. 

Also, how do I ran the following command **adb install -g app/build/outputs/apk/app-debug.apk** if Android studio doesn't recognize adb.

**Comment by Fleker** [comment]
If you reboot the device, the new permissions will be granted.

**Comment by tkamaal** [comment]
Reboot fixed this problem. But I still can't get google assistant working. 

When I do a **run** in Android Studio, I see these following messages . But if I press the button to start recording and request some query. Google assistant doesn't respond. 

01/03 10:33:10: Launching step1-start-here
$ adb install-multiple -r -t C:\Users\tkamaal\Documents\androidthings-googleassistant\step1-start-here\build\intermediates\split-apk\debug\dep\dependencies.apk C:\Users\tkamaal\Documents\androidthings-googleassistant\step1-start-here\build\intermediates\split-apk\debug\slices\slice_0.apk C:\Users\tkamaal\Documents\androidthings-googleassistant\step1-start-here\build\intermediates\split-apk\debug\slices\slice_1.apk C:\Users\tkamaal\Documents\androidthings-googleassistant\step1-start-here\build\intermediates\split-apk\debug\slices\slice_2.apk C:\Users\tkamaal\Documents\androidthings-googleassistant\step1-start-here\build\intermediates\split-apk\debug\slices\slice_3.apk C:\Users\tkamaal\Documents\androidthings-googleassistant\step1-start-here\build\intermediates\split-apk\debug\slices\slice_4.apk C:\Users\tkamaal\Documents\androidthings-googleassistant\step1-start-here\build\intermediates\split-apk\debug\slices\slice_5.apk C:\Users\tkamaal\Documents\androidthings-googleassistant\step1-start-here\build\intermediates\split-apk\debug\slices\slice_6.apk C:\Users\tkamaal\Documents\androidthings-googleassistant\step1-start-here\build\intermediates\split-apk\debug\slices\slice_7.apk C:\Users\tkamaal\Documents\androidthings-googleassistant\step1-start-here\build\intermediates\split-apk\debug\slices\slice_8.apk C:\Users\tkamaal\Documents\androidthings-googleassistant\step1-start-here\build\intermediates\split-apk\debug\slices\slice_9.apk C:\Users\tkamaal\Documents\androidthings-googleassistant\step1-start-here\build\outputs\apk\debug\step1-start-here-debug.apk 
Split APKs installed
$ adb shell am start -n "com.example.androidthings.assistant/com.example.androidthings.assistant.AssistantActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 1193 on device google-iot_rpi3-10.160.3.131:5555
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/AssistantActivity: starting assistant demo
D/AssistantActivity: enumerating devices
I/AssistantActivity: initializing DAC trigger
I/AssistantActivity: setting volume to: 15
D/AudioTrack: Client defaulted notificationFrames to 460 for frameCount 1380
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/vndksupport: Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.



And if I do a **run** again in Android studio, I see the following messages . I'm not using **BCM16** pin on raspberry Pi. I'm using the pins for button and LED mentioned in BoardsDefault.java file which are **BCM23** and **BCM25** respectively.

01/03 10:37:14: Launching step1-start-here
$ adb shell am start -n "com.example.androidthings.assistant/com.example.androidthings.assistant.AssistantActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 1296 on device google-iot_rpi3-10.160.3.131:5555
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/InstantRun: starting instant run server: is main process
I/AssistantActivity: starting assistant demo
D/AssistantActivity: enumerating devices
I/AssistantActivity: initializing DAC trigger
I/AssistantActivity: setting volume to: 15
D/AudioTrack: Client defaulted notificationFrames to 460 for frameCount 1380
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/AssistantActivity: starting assistant demo
D/AssistantActivity: enumerating devices
I/AssistantActivity: initializing DAC trigger
E/AssistantActivity: error configuring peripherals:
                     com.google.android.things.pio.PioException: android.os.ServiceSpecificException: BCM16 is already in use (code 16)
                         at com.google.android.things.pio.GpioImpl.<init>(GpioImpl.java:53)
                         at com.google.android.things.pio.PeripheralManagerService.openGpio(PeripheralManagerService.java:170)
                         at com.google.android.things.contrib.driver.voicehat.Max98357A.<init>(Max98357A.java:59)
                         at com.google.android.things.contrib.driver.voicehat.VoiceHat.openDac(VoiceHat.java:124)
                         at com.example.androidthings.assistant.AssistantActivity.onCreate(AssistantActivity.java:301)
                         at android.app.Activity.performCreate(Activity.java:7000)
                         at android.app.Activity.performCreate(Activity.java:6991)
                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                         at android.app.ActivityThread.-wrap11(Unknown Source:0)
                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                         at android.os.Handler.dispatchMessage(Handler.java:106)
                         at android.os.Looper.loop(Looper.java:164)
                         at android.app.ActivityThread.main(ActivityThread.java:6494)
                         at java.lang.reflect.Method.invoke(Native Method)
                         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                      Caused by: android.os.ServiceSpecificException: BCM16 is already in use (code 16)
                         at android.os.Parcel.readException(Parcel.java:2018)
                         at android.os.Parcel.readException(Parcel.java:1950)
                         at com.google.android.things.pio.IPeripheralManagerClient$Stub$Proxy.OpenGpio(IPeripheralManagerClient.java:776)
                         at com.google.android.things.pio.GpioImpl.<init>(GpioImpl.java:51)
                         at com.google.android.things.pio.PeripheralManagerService.openGpio(PeripheralManagerService.java:170) 
                         at com.google.android.things.contrib.driver.voicehat.Max98357A.<init>(Max98357A.java:59) 
                         at com.google.android.things.contrib.driver.voicehat.VoiceHat.openDac(VoiceHat.java:124) 
                         at com.example.androidthings.assistant.AssistantActivity.onCreate(AssistantActivity.java:301) 
                         at android.app.Activity.performCreate(Activity.java:7000) 
                         at android.app.Activity.performCreate(Activity.java:6991) 
                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                         at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                         at android.os.Handler.dispatchMessage(Handler.java:106) 
                         at android.os.Looper.loop(Looper.java:164) 
                         at android.app.ActivityThread.main(ActivityThread.java:6494) 
                         at java.lang.reflect.Method.invoke(Native Method) 
                         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
D/vndksupport: Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.

**Comment by aabedraba** [comment]
Hey @tkamaal. The second issue I might know how to solve it.
The problem appears right after the message `initializing DAC trigger`. So it might be coming from the next line of code with initializes VoiceHat. The method `VoiceHat.openDac() ` uses the default pin BCM16.
If you want to change the pin you want to initialize the DAC from you have to pass it to the method (e.g. `VoiceHat.openDac("BCM23")`

**Comment by Fleker** [comment]
On the VoiceHat, the DAC trigger pin is on `BCM16`. This is used to disable/enable the microphone. You should not change it to `BCM23` as that's a different GPIO device.

Are you seeing any message relating to recording starting? Are you seeing the LED turn on/off? You will need to press and hold to give an audio query.

If you are seeing the `BCM16` pin being used already, then you may need to force-stop or uninstall any other apps / modules which may still have access to the pin.

**Comment by tkamaal** [comment]
Thank you @aabedraba. 

I'm using USB microphone. Is there a way to use USB microphone?

**Comment by aabedraba** [comment]
Yes, in the README you can see that USB microphone and/or speaker is okay.
To activate it you should modify the input/output in the `AssistantActivity.onCreate()`
`audioInputDevice = findAudioDevice(AudioManager.GET_DEVICES_INPUTS, AudioDeviceInfo.TYPE_USB_DEVICE);
audioOutputDevice = findAudioDevice(AudioManager.GET_DEVICES_OUTPUTS, AudioDeviceInfo.TYPE_USB_DEVICE);`

**Comment by tkamaal** [comment]
Thank you again @aabedraba. Will try that.

**Comment by tkamaal** [comment]
@Fleker 

Following changes are done in **AssistantActivity.java** file. 

Changed the following parameter to false. Since I' not using VOICEHAT_DAC.
`private static final boolean USE_VOICEHAT_DAC = false;`

Added this condition to enable USB Microphone and 3.5mm audio jack speaker. 

```
       else if (!USE_VOICEHAT_DAC){
            Log.i(TAG, "Trying to setup Microphone and Speaker");

            mAudioInputDevice = findAudioDevice(AudioManager.GET_DEVICES_INPUTS,
                    AudioDeviceInfo.TYPE_USB_DEVICE);
            if (mAudioInputDevice == null) {
                Log.i(TAG, "failed to found preferred audio input device");
            }

            mAudioOutputDevice = findAudioDevice(AudioManager.GET_DEVICES_OUTPUTS,
                    AudioDeviceInfo.TYPE_AUX_LINE);
            if (mAudioOutputDevice == null) {
                Log.i(TAG, "failed to found preferred audio output device");
            }
        }
```


**Questions:**
1. TYPE_AUX_LINE isn't recognized. Which type should I use for 3.5mm speaker. 
2. AUDIO_USE_I2S_VOICEHAT_IF_AVAILABLE = false I don't see this in AssistantActivity.java file. 

Please, do let me know if there any other changes required to get this working.

**Comment by tkamaal** [comment]
Thank you @Fleker and @aabedraba I was able to get it working.
